services:
  postgres:
    image: postgres:16-alpine
    container_name: fx-doc-processor-postgres
    environment:
      POSTGRES_DB: doc_processor_db
      POSTGRES_USER: priyank
      POSTGRES_PASSWORD: priyank
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U priyank -d doc_processor_db" ]
      interval: 10s
      timeout: 5s
      retries: 5

  document-processor:
    image: fx-doc-processor:latest
    build: .
    container_name: fx-doc-processor-app
    env_file:
      - .env
    ports:
      - "${APP_PORT}:8080"
    depends_on:
      postgres:
        condition: service_healthy
    restart: on-failure

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: fx-doc-processor-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "16543:80"
    depends_on:
      - postgres



volumes:
  postgres-data:
    driver: local