server:
  port: ${APP_PORT}
  servlet:
    context-path: /api/document-processor

spring:
  profiles:
    active: ${ACTIVE_PROFILE}
  application:
    name: ${SPRING_APPLICATION_NAME}

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    hikari:
      pool-name: ${DB_POOL_NAME}
      maximum-pool-size: ${DB_CONN_MAX_POOL_SIZE}
      minimum-idle: ${DB_MIN_IDLE}
      connection-timeout: ${DB_CONNECTION_TIMEOUT_MS}
      idle-timeout: ${DB_IDLE_TIMEOUT_MS}
      max-lifetime: ${DB_MAX_LIFETIME_MS}
      validation-timeout: ${DB_VALIDATION_TIMEOUT_MS}
      leak-detection-threshold: ${DB_LEAK_DETECTION_THRESHOLD_MS}
      connection-test-query: SELECT 1
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: ${JPA_JDBC_BATCH_SIZE}
          fetch_size: ${JPA_JDBC_FETCH_SIZE}
        order_inserts: true
        order_updates: true
    mapping-resources:
      - jpa-queries/doc-process-view-queries.xml
      - jpa-queries/file-master-queries.xml
      - jpa-queries/gx-master-queries.xml
      - jpa-queries/zip-master-queries.xml

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

  task:
    execution:
      pool:
        core-size: ${TASK_POOL_CORE_SIZE}
        max-size: ${TASK_POOL_MAX_SIZE}
        queue-capacity: ${TASK_QUEUE_CAPACITY}
        allow-core-thread-timeout: true
        keep-alive: 60s
      shutdown:
        await-termination: true
        await-termination-period: 30s

app:
  sqs:
    listener:
      zip-process-queue:
        concurrency-limit: ${APP_SQS_LISTENER_ZIP_PROCESS_QUEUE_CONCURRENCY_LIMIT}
        max-messages-per-poll: ${APP_SQS_LISTENER_ZIP_PROCESS_QUEUE_MAX_MESSAGE_PER_POLL}
        poll-timeout-seconds: ${APP_SQS_LISTENER_ZIP_PROCESS_QUEUE_POLL_TIMEOUT_SECONDS}
      file-process-queue:
        concurrency-limit: ${APP_SQS_LISTENER_FILE_PROCESS_QUEUE_CONCURRENCY_LIMIT}
        max-messages-per-poll: ${APP_SQS_LISTENER_FILE_PROCESS_QUEUE_MAX_MESSAGE_PER_POLL}
        poll-timeout-seconds: ${APP_SQS_LISTENER_FILE_PROCESS_QUEUE_POLL_TIMEOUT_SECONDS}
  jodconverter:
    office:
      home: ${APP_JOD_CONVERTER_OFFICE_HOME}
      port-numbers: ${APP_JOD_CONVERTER_PORT_NUMBERS}
      task-execution-timeout: ${APP_JOD_CONVERTER_TASK_EXE_TIMEOUT_MS}

  processing:
    max-file-size: ${APP_PROCESSING_FILE_MAX_BYTES_SIZE}
    max-pages: ${APP_PROCESSING_MAX_PAGES}
    pdf:
      optimize: ${APP_PROCESSING_PDF_OPTIMIZE}
      qpdf:
        retry:
          attempts: ${APP_PROCESSING_PDF_QPDF_RETRY_ATTEMPTS}
          delay-ms: ${APP_PROCESSING_PDF_QPDF_RETRY_DELAY_MS}
      ghostscript:
        preset: ${APP_PROCESSING_PDF_GHOSTSCRIPT_PRESET}
        optimization-timeout-minutes: ${APP_PROCESSING_PDF_GHOSTSCRIPT_OPTIMIZATION_TIMEOUT_MINUTES}
        retry:
          attempts: ${APP_PROCESSING_PDF_GHOSTSCRIPT_RETRY_ATTEMPTS}
          delay-ms: ${APP_PROCESSING_PDF_GHOSTSCRIPT_RETRY_DELAY_MS}
    libreoffice:
      retry:
        attempts: ${APP_PROCESSING_LIBREOFFICE_RETRY_ATTEMPTS}
        delay-ms: ${APP_PROCESSING_LIBREOFFICE_RETRY_DELAY_MS}
    msg-handler:
      retry:
        attempts: ${APP_PROCESSING_MSG_HANDLER_RETRY_ATTEMPTS}
        delay-ms: ${APP_PROCESSING_MSG_HANDLER_RETRY_DELAY_MS}
    zip-handler:
      concurrency-limit: ${APP_PROCESSING_ZIP_HANDLER_CONCURRENCY_LIMIT}
      temp-dir: ${APP_PROCESSING_ZIP_HANDLER_TEMP_DIR:/tmp/zip-processing}
      retry:
        attempts: ${APP_PROCESSING_ZIP_HANDLER_RETRY_ATTEMPTS}
        delay-ms: ${APP_PROCESSING_ZIP_HANDLER_RETRY_DELAY_MS}

  scheduler:
    gx-doc-upload: ${APP_SCHEDULER_GX_DOC_UPLOAD}
    fetch-doc-upload-status: ${APP_SCHEDULER_FETCH_DOC_UPLOAD_STATUS}
    stale-job: ${APP_SCHEDULER_STALE_JOB}
    stale-job-cleanup-hours: ${APP_SCHEDULER_STALE_JOB_CLEANUP_HOURS}
    job-completion-check: ${APP_SCHEDULER_JOB_COMPLETION_CHECK}

  gx-client:
    baseurl: ${APP_GX_CLIENT_BASEURL}
    auth-key-name: ${APP_GX_CLIENT_AUTH_KEY_NAME}
    auth-key-value: ${APP_GX_CLIENT_AUTH_KEY_VALUE}
    endpoint:
      upload-file: ${APP_GX_CLIENT_ENDPOINT_UPLOAD_FILE}
      fetch-status: ${APP_GX_CLIENT_ENDPOINT_FETCH_STATUS}
      create-bucket: ${APP_GX_CLIENT_ENDPOINT_CREATE_BUCKET}

  gx:
    max-process: ${APP_GX_MAX_CONCURRENT_UPLOADS}

aws:
  region: ${AWS_REGION}
  s3:
    bucket: ${AWS_S3_BUCKET}
    presigned-url-duration-minutes: ${AWS_S3_PRESIGNED_URL_DURATION_MINUTES}
    retry-count: ${S3_RETRY_COUNT}
  access-key: ${AWS_ACCESS_KEY}
  secret-key: ${AWS_SECRET_KEY}
  sqs:
    zip-queue-name: ${AWS_SQS_ZIP_QUEUE_NAME}
    file-queue-name: ${AWS_SQS_FILE_QUEUE_NAME}
